"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import victor_lcm_interface.cartesian_value_quantity

class cartesian_path_execution_parameters(object):
    __slots__ = ["max_velocity", "max_acceleration", "max_nullspace_velocity", "max_nullspace_acceleration"]

    def __init__(self):
        self.max_velocity = victor_lcm_interface.cartesian_value_quantity()
        self.max_acceleration = victor_lcm_interface.cartesian_value_quantity()
        self.max_nullspace_velocity = 0.0
        self.max_nullspace_acceleration = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(cartesian_path_execution_parameters._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.max_velocity._get_packed_fingerprint() == victor_lcm_interface.cartesian_value_quantity._get_packed_fingerprint()
        self.max_velocity._encode_one(buf)
        assert self.max_acceleration._get_packed_fingerprint() == victor_lcm_interface.cartesian_value_quantity._get_packed_fingerprint()
        self.max_acceleration._encode_one(buf)
        buf.write(struct.pack(">dd", self.max_nullspace_velocity, self.max_nullspace_acceleration))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cartesian_path_execution_parameters._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cartesian_path_execution_parameters._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cartesian_path_execution_parameters()
        self.max_velocity = victor_lcm_interface.cartesian_value_quantity._decode_one(buf)
        self.max_acceleration = victor_lcm_interface.cartesian_value_quantity._decode_one(buf)
        self.max_nullspace_velocity, self.max_nullspace_acceleration = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cartesian_path_execution_parameters in parents: return 0
        newparents = parents + [cartesian_path_execution_parameters]
        tmphash = (0xa5c0017a3cb11d5d+ victor_lcm_interface.cartesian_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.cartesian_value_quantity._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cartesian_path_execution_parameters._packed_fingerprint is None:
            cartesian_path_execution_parameters._packed_fingerprint = struct.pack(">Q", cartesian_path_execution_parameters._get_hash_recursive([]))
        return cartesian_path_execution_parameters._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

