"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import victor_lcm_interface.cartesian_value_quantity

class cartesian_impedance_parameters(object):
    __slots__ = ["cartesian_stiffness", "nullspace_stiffness", "cartesian_damping", "nullspace_damping"]

    def __init__(self):
        self.cartesian_stiffness = victor_lcm_interface.cartesian_value_quantity()
        self.nullspace_stiffness = 0.0
        self.cartesian_damping = victor_lcm_interface.cartesian_value_quantity()
        self.nullspace_damping = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(cartesian_impedance_parameters._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.cartesian_stiffness._get_packed_fingerprint() == victor_lcm_interface.cartesian_value_quantity._get_packed_fingerprint()
        self.cartesian_stiffness._encode_one(buf)
        buf.write(struct.pack(">d", self.nullspace_stiffness))
        assert self.cartesian_damping._get_packed_fingerprint() == victor_lcm_interface.cartesian_value_quantity._get_packed_fingerprint()
        self.cartesian_damping._encode_one(buf)
        buf.write(struct.pack(">d", self.nullspace_damping))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cartesian_impedance_parameters._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cartesian_impedance_parameters._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cartesian_impedance_parameters()
        self.cartesian_stiffness = victor_lcm_interface.cartesian_value_quantity._decode_one(buf)
        self.nullspace_stiffness = struct.unpack(">d", buf.read(8))[0]
        self.cartesian_damping = victor_lcm_interface.cartesian_value_quantity._decode_one(buf)
        self.nullspace_damping = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cartesian_impedance_parameters in parents: return 0
        newparents = parents + [cartesian_impedance_parameters]
        tmphash = (0x46a21e6d7f654ba8+ victor_lcm_interface.cartesian_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.cartesian_value_quantity._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cartesian_impedance_parameters._packed_fingerprint is None:
            cartesian_impedance_parameters._packed_fingerprint = struct.pack(">Q", cartesian_impedance_parameters._get_hash_recursive([]))
        return cartesian_impedance_parameters._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

