"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cartesian_value_quantity(object):
    __slots__ = ["x", "y", "z", "a", "b", "c"]

    def __init__(self):
        self.x = 0.0
        self.y = 0.0
        self.z = 0.0
        self.a = 0.0
        self.b = 0.0
        self.c = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(cartesian_value_quantity._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">dddddd", self.x, self.y, self.z, self.a, self.b, self.c))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cartesian_value_quantity._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cartesian_value_quantity._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cartesian_value_quantity()
        self.x, self.y, self.z, self.a, self.b, self.c = struct.unpack(">dddddd", buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cartesian_value_quantity in parents: return 0
        tmphash = (0xf31b4152afd20ada) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cartesian_value_quantity._packed_fingerprint is None:
            cartesian_value_quantity._packed_fingerprint = struct.pack(">Q", cartesian_value_quantity._get_hash_recursive([]))
        return cartesian_value_quantity._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

