"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cartesian_pose(object):
    __slots__ = ["xt", "yt", "zt", "wr", "xr", "yr", "zr"]

    def __init__(self):
        self.xt = 0.0
        self.yt = 0.0
        self.zt = 0.0
        self.wr = 0.0
        self.xr = 0.0
        self.yr = 0.0
        self.zr = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(cartesian_pose._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddddddd", self.xt, self.yt, self.zt, self.wr, self.xr, self.yr, self.zr))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cartesian_pose._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cartesian_pose._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cartesian_pose()
        self.xt, self.yt, self.zt, self.wr, self.xr, self.yr, self.zr = struct.unpack(">ddddddd", buf.read(56))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cartesian_pose in parents: return 0
        tmphash = (0x907f5fa40101a992) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cartesian_pose._packed_fingerprint is None:
            cartesian_pose._packed_fingerprint = struct.pack(">Q", cartesian_pose._get_hash_recursive([]))
        return cartesian_pose._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

