"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class control_mode(object):
    __slots__ = ["mode"]

    IS_POSITION_MOTION = 0
    IS_CARTESIAN_MOTION = 1
    IS_IMPEDANCE_CONTROL = 2
    JOINT_POSITION = 0
    JOINT_IMPEDANCE = 2
    CARTESIAN_POSE = 1
    CARTESIAN_IMPEDANCE = 3

    def __init__(self):
        self.mode = 0

    def encode(self):
        buf = BytesIO()
        buf.write(control_mode._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.mode))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_mode._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_mode._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = control_mode()
        self.mode = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if control_mode in parents: return 0
        tmphash = (0x90e9a182ecc1c212) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if control_mode._packed_fingerprint is None:
            control_mode._packed_fingerprint = struct.pack(">Q", control_mode._get_hash_recursive([]))
        return control_mode._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

