"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class joint_value_quantity(object):
    __slots__ = ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6", "joint_7"]

    def __init__(self):
        self.joint_1 = 0.0
        self.joint_2 = 0.0
        self.joint_3 = 0.0
        self.joint_4 = 0.0
        self.joint_5 = 0.0
        self.joint_6 = 0.0
        self.joint_7 = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(joint_value_quantity._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddddddd", self.joint_1, self.joint_2, self.joint_3, self.joint_4, self.joint_5, self.joint_6, self.joint_7))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_value_quantity._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_value_quantity._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = joint_value_quantity()
        self.joint_1, self.joint_2, self.joint_3, self.joint_4, self.joint_5, self.joint_6, self.joint_7 = struct.unpack(">ddddddd", buf.read(56))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if joint_value_quantity in parents: return 0
        tmphash = (0x15589646573911e7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if joint_value_quantity._packed_fingerprint is None:
            joint_value_quantity._packed_fingerprint = struct.pack(">Q", joint_value_quantity._get_hash_recursive([]))
        return joint_value_quantity._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

