"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class joint_path_execution_parameters(object):
    __slots__ = ["joint_relative_velocity", "joint_relative_acceleration", "override_joint_acceleration"]

    def __init__(self):
        self.joint_relative_velocity = 0.0
        self.joint_relative_acceleration = 0.0
        self.override_joint_acceleration = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(joint_path_execution_parameters._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.joint_relative_velocity, self.joint_relative_acceleration, self.override_joint_acceleration))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_path_execution_parameters._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_path_execution_parameters._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = joint_path_execution_parameters()
        self.joint_relative_velocity, self.joint_relative_acceleration, self.override_joint_acceleration = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if joint_path_execution_parameters in parents: return 0
        tmphash = (0x31db436c85aab16c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if joint_path_execution_parameters._packed_fingerprint is None:
            joint_path_execution_parameters._packed_fingerprint = struct.pack(">Q", joint_path_execution_parameters._get_hash_recursive([]))
        return joint_path_execution_parameters._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

