# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    # TODO: how is the order determined??? since both the trajectory and position controllers claim the same hardware resources???
    - left_arm_position_controller
    - right_arm_position_controller
    - joint_trajectory_controller
    - left_force_torque_broadcaster
    - right_force_torque_broadcaster