# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - both_arms_controller
    - left_force_torque_broadcaster
    - right_force_torque_broadcaster

  both_arms_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
    action_ns: follow_joint_trajectory
    default: true