# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # These are derived from the standard ros2 controllers, but with added control mode parameters
    joint_position_trajectory_controller:
      type: victor_hardware/KukaJointPositionTrajectoryController

    left_arm_position_controller:
      type: position_controllers/JointGroupPositionController

    right_arm_position_controller:
      type: position_controllers/JointGroupPositionController

    left_arm_cartesian_controller:
      type: victor_hardware/KukaCartesianController

    right_arm_cartesian_controller:
      type: victor_hardware/KukaCartesianController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    right_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

joint_position_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position

left_arm_position_controller:
  ros__parameters:
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
    interface_name: position

right_arm_position_controller:
  ros__parameters:
    joints:
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
    interface_name: position

left_arm_cartesian_controller:
  ros__parameters:
    side: left

right_arm_cartesian_controller:
  ros__parameters:
    side: right

left_force_torque_broadcaster:
  ros__parameters:
    frame_id: victor_left_sunrise_palm_surface
    sensor_name: left_force_torque_sensor

right_force_torque_broadcaster:
  ros__parameters:
    frame_id: victor_right_sunrise_palm_surface
    sensor_name: right_force_torque_sensor