# This config file is used by ros2_control
# the mode numbers used are defined by the LCM control_mode message
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # These are derived from the standard ros2 controllers, but with added control mode parameters
    joint_position_trajectory_controller:
      type: victor_hardware/KukaJointTrajectoryController

    joint_impedance_trajectory_controller:
      type: victor_hardware/KukaJointTrajectoryController

    left_arm_position_controller:
      type: victor_hardware/KukaJointGroupPositionController

    left_arm_impedance_controller:
      type: victor_hardware/KukaJointGroupPositionController

    right_arm_position_controller:
      type: victor_hardware/KukaJointGroupPositionController

    right_arm_impedance_controller:
      type: victor_hardware/KukaJointGroupPositionController

    left_arm_cartesian_controller:
      type: victor_hardware/KukaCartesianController

    right_arm_cartesian_controller:
      type: victor_hardware/KukaCartesianController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    right_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

joint_position_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
    control_mode: joint_position

joint_impedance_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
    control_mode: joint_impedance

left_arm_position_controller:
  ros__parameters:
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
    interface_name: position
    side: left # This tells us which LCM url to talk to
    control_mode: joint_position # this is the command mode interface name in ros2 control

left_arm_impedance_controller:
  ros__parameters:
    joints:
      - victor_left_arm_joint_1
      - victor_left_arm_joint_2
      - victor_left_arm_joint_3
      - victor_left_arm_joint_4
      - victor_left_arm_joint_5
      - victor_left_arm_joint_6
      - victor_left_arm_joint_7
    interface_name: position
    side: left
    control_mode: joint_impedance

right_arm_position_controller:
  ros__parameters:
    joints:
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
    interface_name: position
    side: right
    control_mode: joint_position

right_arm_impedance_controller:
  ros__parameters:
    joints:
      - victor_right_arm_joint_1
      - victor_right_arm_joint_2
      - victor_right_arm_joint_3
      - victor_right_arm_joint_4
      - victor_right_arm_joint_5
      - victor_right_arm_joint_6
      - victor_right_arm_joint_7
    interface_name: position
    side: right
    control_mode: joint_impedance

left_arm_cartesian_controller:
  ros__parameters:
    side: left
    control_mode: cartesian_impedance

right_arm_cartesian_controller:
  ros__parameters:
    side: right
    control_mode: cartesian_impedance

left_force_torque_broadcaster:
  ros__parameters:
    frame_id: victor_left_sunrise_palm_surface
    sensor_name: left_force_torque_sensor

right_force_torque_broadcaster:
  ros__parameters:
    frame_id: victor_right_sunrise_palm_surface
    sensor_name: right_force_torque_sensor
