# NOTE: these gains are used by gazebo when a position interface is used.
# IF these gains are NOT loaded, gazebo uses a kinematic controllers
# IF they are loaded, gazebo uses a PID from position to position to control the joints (equivalent to an effort interface, but inside gazebo)

victor:
  gazebo_ros_control:
    pid_gains:
      victor_left_arm_joint_1:
        p: 500
        i: 0.0
        d: 0.0
      victor_left_arm_joint_2:
        p: 500
        i: 0.0
        d: 0.0
      victor_left_arm_joint_3:
        p: 500
        i: 0.0
        d: 0.0
      victor_left_arm_joint_4:
        p: 500
        i: 0.0
        d: 0.0
      victor_left_arm_joint_5:
        p: 500
        i: 0.0
        d: 0.0
      victor_left_arm_joint_6:
        p: 500
        i: 0.0
        d: 0.0
      victor_left_arm_joint_7:
        p: 500
        i: 0.0
        d: 0.0
      victor_right_arm_joint_1:
        p: 500
        i: 0.0
        d: 0.0
      victor_right_arm_joint_2:
        p: 500
        i: 0.0
        d: 0.0
      victor_right_arm_joint_3:
        p: 500
        i: 0.0
        d: 0.0
      victor_right_arm_joint_4:
        p: 500
        i: 0.0
        d: 0.0
      victor_right_arm_joint_5:
        p: 500
        i: 0.0
        d: 0.0
      victor_right_arm_joint_6:
        p: 500
        i: 0.0
        d: 0.0
      victor_right_arm_joint_7:
        p: 500
        i: 0.0
        d: 0.0
