/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package wiktor_hardware_interface;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motion_status implements lcm.lcm.LCMEncodable
{
    public wiktor_hardware_interface.joint_value_quantity measured_joint_position;
    public wiktor_hardware_interface.joint_value_quantity commanded_joint_position;
    public wiktor_hardware_interface.joint_value_quantity measured_joint_velocity;
    public wiktor_hardware_interface.joint_value_quantity measured_joint_torque;
    public wiktor_hardware_interface.joint_value_quantity estimated_external_torque;
    public wiktor_hardware_interface.cartesian_value_quantity measured_cartesian_pose;
    public wiktor_hardware_interface.cartesian_value_quantity commanded_cartesian_pose;
    public wiktor_hardware_interface.cartesian_value_quantity estimated_external_wrench;
    public double timestamp;
    public byte active_control_mode;
 
    public motion_status()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x76f416e8bc4561d8L;
 
    public static final byte IS_POSITION_MOTION = (byte) 0;
    public static final byte IS_CARTESIAN_MOTION = (byte) 1;
    public static final byte IS_IMPEDANCE_CONTROL = (byte) 2;
    public static final byte JOINT_POSITION = (byte) 0;
    public static final byte JOINT_IMPEDANCE = (byte) 2;
    public static final byte CARTESIAN_POSE = (byte) 1;
    public static final byte CARTESIAN_IMPEDANCE = (byte) 3;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(wiktor_hardware_interface.motion_status.class))
            return 0L;
 
        classes.add(wiktor_hardware_interface.motion_status.class);
        long hash = LCM_FINGERPRINT_BASE
             + wiktor_hardware_interface.joint_value_quantity._hashRecursive(classes)
             + wiktor_hardware_interface.joint_value_quantity._hashRecursive(classes)
             + wiktor_hardware_interface.joint_value_quantity._hashRecursive(classes)
             + wiktor_hardware_interface.joint_value_quantity._hashRecursive(classes)
             + wiktor_hardware_interface.joint_value_quantity._hashRecursive(classes)
             + wiktor_hardware_interface.cartesian_value_quantity._hashRecursive(classes)
             + wiktor_hardware_interface.cartesian_value_quantity._hashRecursive(classes)
             + wiktor_hardware_interface.cartesian_value_quantity._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.measured_joint_position._encodeRecursive(outs); 
 
        this.commanded_joint_position._encodeRecursive(outs); 
 
        this.measured_joint_velocity._encodeRecursive(outs); 
 
        this.measured_joint_torque._encodeRecursive(outs); 
 
        this.estimated_external_torque._encodeRecursive(outs); 
 
        this.measured_cartesian_pose._encodeRecursive(outs); 
 
        this.commanded_cartesian_pose._encodeRecursive(outs); 
 
        this.estimated_external_wrench._encodeRecursive(outs); 
 
        outs.writeDouble(this.timestamp); 
 
        outs.writeByte(this.active_control_mode); 
 
    }
 
    public motion_status(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motion_status(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static wiktor_hardware_interface.motion_status _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        wiktor_hardware_interface.motion_status o = new wiktor_hardware_interface.motion_status();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.measured_joint_position = wiktor_hardware_interface.joint_value_quantity._decodeRecursiveFactory(ins);
 
        this.commanded_joint_position = wiktor_hardware_interface.joint_value_quantity._decodeRecursiveFactory(ins);
 
        this.measured_joint_velocity = wiktor_hardware_interface.joint_value_quantity._decodeRecursiveFactory(ins);
 
        this.measured_joint_torque = wiktor_hardware_interface.joint_value_quantity._decodeRecursiveFactory(ins);
 
        this.estimated_external_torque = wiktor_hardware_interface.joint_value_quantity._decodeRecursiveFactory(ins);
 
        this.measured_cartesian_pose = wiktor_hardware_interface.cartesian_value_quantity._decodeRecursiveFactory(ins);
 
        this.commanded_cartesian_pose = wiktor_hardware_interface.cartesian_value_quantity._decodeRecursiveFactory(ins);
 
        this.estimated_external_wrench = wiktor_hardware_interface.cartesian_value_quantity._decodeRecursiveFactory(ins);
 
        this.timestamp = ins.readDouble();
 
        this.active_control_mode = ins.readByte();
 
    }
 
    public wiktor_hardware_interface.motion_status copy()
    {
        wiktor_hardware_interface.motion_status outobj = new wiktor_hardware_interface.motion_status();
        outobj.measured_joint_position = this.measured_joint_position.copy();
 
        outobj.commanded_joint_position = this.commanded_joint_position.copy();
 
        outobj.measured_joint_velocity = this.measured_joint_velocity.copy();
 
        outobj.measured_joint_torque = this.measured_joint_torque.copy();
 
        outobj.estimated_external_torque = this.estimated_external_torque.copy();
 
        outobj.measured_cartesian_pose = this.measured_cartesian_pose.copy();
 
        outobj.commanded_cartesian_pose = this.commanded_cartesian_pose.copy();
 
        outobj.estimated_external_wrench = this.estimated_external_wrench.copy();
 
        outobj.timestamp = this.timestamp;
 
        outobj.active_control_mode = this.active_control_mode;
 
        return outobj;
    }
 
}

