"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import victor_lcm_interface.control_mode

import victor_lcm_interface.cartesian_value_quantity

import victor_lcm_interface.joint_value_quantity

import victor_lcm_interface.cartesian_pose

class motion_status(object):
    __slots__ = ["measured_joint_position", "commanded_joint_position", "measured_joint_velocity", "measured_joint_torque", "estimated_external_torque", "estimated_external_wrench", "measured_cartesian_pose_abc", "commanded_cartesian_pose_abc", "measured_cartesian_pose", "commanded_cartesian_pose", "active_control_mode", "timestamp"]

    def __init__(self):
        self.measured_joint_position = victor_lcm_interface.joint_value_quantity()
        self.commanded_joint_position = victor_lcm_interface.joint_value_quantity()
        self.measured_joint_velocity = victor_lcm_interface.joint_value_quantity()
        self.measured_joint_torque = victor_lcm_interface.joint_value_quantity()
        self.estimated_external_torque = victor_lcm_interface.joint_value_quantity()
        self.estimated_external_wrench = victor_lcm_interface.cartesian_value_quantity()
        self.measured_cartesian_pose_abc = victor_lcm_interface.cartesian_value_quantity()
        self.commanded_cartesian_pose_abc = victor_lcm_interface.cartesian_value_quantity()
        self.measured_cartesian_pose = victor_lcm_interface.cartesian_pose()
        self.commanded_cartesian_pose = victor_lcm_interface.cartesian_pose()
        self.active_control_mode = victor_lcm_interface.control_mode()
        self.timestamp = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(motion_status._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.measured_joint_position._get_packed_fingerprint() == victor_lcm_interface.joint_value_quantity._get_packed_fingerprint()
        self.measured_joint_position._encode_one(buf)
        assert self.commanded_joint_position._get_packed_fingerprint() == victor_lcm_interface.joint_value_quantity._get_packed_fingerprint()
        self.commanded_joint_position._encode_one(buf)
        assert self.measured_joint_velocity._get_packed_fingerprint() == victor_lcm_interface.joint_value_quantity._get_packed_fingerprint()
        self.measured_joint_velocity._encode_one(buf)
        assert self.measured_joint_torque._get_packed_fingerprint() == victor_lcm_interface.joint_value_quantity._get_packed_fingerprint()
        self.measured_joint_torque._encode_one(buf)
        assert self.estimated_external_torque._get_packed_fingerprint() == victor_lcm_interface.joint_value_quantity._get_packed_fingerprint()
        self.estimated_external_torque._encode_one(buf)
        assert self.estimated_external_wrench._get_packed_fingerprint() == victor_lcm_interface.cartesian_value_quantity._get_packed_fingerprint()
        self.estimated_external_wrench._encode_one(buf)
        assert self.measured_cartesian_pose_abc._get_packed_fingerprint() == victor_lcm_interface.cartesian_value_quantity._get_packed_fingerprint()
        self.measured_cartesian_pose_abc._encode_one(buf)
        assert self.commanded_cartesian_pose_abc._get_packed_fingerprint() == victor_lcm_interface.cartesian_value_quantity._get_packed_fingerprint()
        self.commanded_cartesian_pose_abc._encode_one(buf)
        assert self.measured_cartesian_pose._get_packed_fingerprint() == victor_lcm_interface.cartesian_pose._get_packed_fingerprint()
        self.measured_cartesian_pose._encode_one(buf)
        assert self.commanded_cartesian_pose._get_packed_fingerprint() == victor_lcm_interface.cartesian_pose._get_packed_fingerprint()
        self.commanded_cartesian_pose._encode_one(buf)
        assert self.active_control_mode._get_packed_fingerprint() == victor_lcm_interface.control_mode._get_packed_fingerprint()
        self.active_control_mode._encode_one(buf)
        buf.write(struct.pack(">d", self.timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motion_status._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motion_status._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motion_status()
        self.measured_joint_position = victor_lcm_interface.joint_value_quantity._decode_one(buf)
        self.commanded_joint_position = victor_lcm_interface.joint_value_quantity._decode_one(buf)
        self.measured_joint_velocity = victor_lcm_interface.joint_value_quantity._decode_one(buf)
        self.measured_joint_torque = victor_lcm_interface.joint_value_quantity._decode_one(buf)
        self.estimated_external_torque = victor_lcm_interface.joint_value_quantity._decode_one(buf)
        self.estimated_external_wrench = victor_lcm_interface.cartesian_value_quantity._decode_one(buf)
        self.measured_cartesian_pose_abc = victor_lcm_interface.cartesian_value_quantity._decode_one(buf)
        self.commanded_cartesian_pose_abc = victor_lcm_interface.cartesian_value_quantity._decode_one(buf)
        self.measured_cartesian_pose = victor_lcm_interface.cartesian_pose._decode_one(buf)
        self.commanded_cartesian_pose = victor_lcm_interface.cartesian_pose._decode_one(buf)
        self.active_control_mode = victor_lcm_interface.control_mode._decode_one(buf)
        self.timestamp = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if motion_status in parents: return 0
        newparents = parents + [motion_status]
        tmphash = (0x8d25644d75239c66+ victor_lcm_interface.joint_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.joint_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.joint_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.joint_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.joint_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.cartesian_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.cartesian_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.cartesian_value_quantity._get_hash_recursive(newparents)+ victor_lcm_interface.cartesian_pose._get_hash_recursive(newparents)+ victor_lcm_interface.cartesian_pose._get_hash_recursive(newparents)+ victor_lcm_interface.control_mode._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motion_status._packed_fingerprint is None:
            motion_status._packed_fingerprint = struct.pack(">Q", motion_status._get_hash_recursive([]))
        return motion_status._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

